[package]
name = "TrusTrain"
version = "0.1.0"

[dependencies]
AptosFramework = { local = "C:/Users/LENOVO/Desktop/aptos-core-main/aptos-move/framework/aptos-framework" , rev="testnet" }


[addresses]
TrusTrain="0xba910884da53913141fdfa5402d9eb75ef3822183be3c38611e0f732b13ec3e3"
aptos_framework = "0x1"
move_stdlib = "0x1"
